# Generated by Django 2.0.7 on 2018-11-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=1024, verbose_name='标签')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '请求头',
                'db_table': 'ApiHead',
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('httpType', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=50, verbose_name='http/https')),
                ('requestType', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=50, verbose_name='请求方式')),
                ('apiAddress', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('requestParameterType', models.CharField(choices=[('form-data', '表单(form-data)'), ('raw', '源数据(raw)'), ('Restful', 'Restful')], max_length=50, verbose_name='请求参数格式')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '接口信息',
                'db_table': 'ApiInfo',
            },
        ),
        migrations.CreateModel(
            name='ApiParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数值')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('belong_Api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ApiInfo')),
            ],
            options={
                'verbose_name': '请求参数',
                'db_table': 'ApiParameter',
            },
        ),
        migrations.CreateModel(
            name='ApiParameterRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('belong_Api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ApiInfo')),
            ],
            options={
                'verbose_name': '请求参数Raw',
                'db_table': 'ApiParameterRaw',
            },
        ),
        migrations.CreateModel(
            name='ApiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='参数名')),
                ('type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='参数值')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('belong_Api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ApiInfo')),
            ],
            options={
                'verbose_name': '返回参数',
                'db_table': 'ApiResponse',
            },
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('test_user', models.CharField(max_length=50, verbose_name='测试负责人')),
                ('simple_desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
                ('other_desc', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
            ],
            options={
                'verbose_name': '模块信息',
                'db_table': 'ModuleInfo',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('responsible_name', models.CharField(max_length=20, verbose_name='负责人')),
                ('test_user', models.CharField(max_length=100, verbose_name='测试人员')),
                ('dev_user', models.CharField(max_length=100, verbose_name='开发人员')),
                ('publish_app', models.CharField(max_length=100, verbose_name='发布应用')),
                ('simple_desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
                ('other_desc', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'ProjectInfo',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='任务名')),
                ('type', models.CharField(choices=[('everyday', '每天'), ('once', '一次'), ('Mon-fri', '工作日')], max_length=50, verbose_name='类型')),
                ('executeTime', models.DateTimeField(max_length=50, verbose_name='执行时间')),
                ('fixedTime', models.TimeField(max_length=50, verbose_name='固定时间')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo')),
            ],
            options={
                'verbose_name': '定时任务',
                'db_table': 'TaskInfo',
            },
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='belong_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ModuleInfo'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo'),
        ),
        migrations.AddField(
            model_name='apihead',
            name='belong_Api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ApiInfo'),
        ),
    ]
