# Generated by Django 2.0.7 on 2018-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0003_auto_20180709_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiparameter',
            name='required',
            field=models.BooleanField(default=False, verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='required',
            field=models.BooleanField(default=False, verbose_name='是否必填'),
        ),
    ]
